// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htnrrslfzazzauovvdnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0bnJyc2xmemF6emF1b3Z2ZG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzg4ODYsImV4cCI6MjA2ODkxNDg4Nn0.o2H0NOhzWTl2a_m0wqDEvpmLWPbNO0ezAJPPfw-bAOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});